<a href="https://colab.research.google.com/github/ARPIT-SINGHAL-22102003/DATA_SCIENCE/blob/main/Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **IMPORTRING NUMPY**

In [1]:
import numpy as np

# **NUMPY CREATING ARRAYS**

In [9]:
# Using Numpy Function

# 1-D Array

array = np.arange(20)
print(array)

print(array.shape) # to check the dimensions of array


# 2D array

array_1 = np.arange(20).reshape(10,2)
print(array_1)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [11]:
# Conversions from python structures like list
array = np.array([4,5,6])
print(array)

list = [4,5,6]
print(list)

[4 5 6]
[4, 5, 6]


In [17]:
# Using library functions

np.zeros((2,4))
np.ones((3,6))
np.full((2,2),3)

array([[3, 3],
       [3, 3]])

In [28]:
# Array with Ndarray

# 0d array

arr = np.array(42)
print(arr)

# 1d array
print("---------------------------------------------------")


arr_1 = np.array([1, 2, 3, 4, 5])
print(arr_1)

# 2d array
print("---------------------------------------------------")

arr_2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2)

# 3d array
print("---------------------------------------------------")

arr_3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr_3)

# Higher Dimensional array

print("---------------------------------------------------")

arr_n = np.array([1, 2, 3, 4], ndmin=9)
print(arr_n)

42
---------------------------------------------------
[1 2 3 4 5]
---------------------------------------------------
[[1 2 3]
 [4 5 6]]
---------------------------------------------------
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
---------------------------------------------------
[[[[[[[[[1 2 3 4]]]]]]]]]


# **NUMPY ARRAY ATTRIBUTES**

In [29]:
# ndim: returns number of dimension of the array
# size: returns number of elements in the array
# dtype: returns data type of elements in the array
# shape: returns the size of the array in each dimension.
# itemsize: returns the size (in bytes) of each elements in the array
# data: returns the buffer containing actual elements of the array in memory